name: dirework

services:
  postgres:
    image: postgres:17-alpine
    container_name: dirework-postgres
    environment:
      POSTGRES_DB: dirework
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - dirework_postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  dirework_postgres_data:
